CC = gcc
SEP = ;
CFLAGS = -Wall
EXEC = prog

manuel:
	gcc -c *c $(SEP) gcc -o prog *.o $(SEP) ./prog

auto:
	gcc -c *c $(SEP) gcc -o prog *.o $(SEP) ./prog commandes.txt

clean:
	rm chemin.o $(SEP) rm noeud.o $(SEP) rm shell.o $(SEP) rm prog